package com.grupo06.forms;

import com.grupo06.View.CustomTable.CustomTable;
import com.grupo06.View.customPanel.ButtonInfoPanel;
import java.awt.Dimension;

/**
 *
 * @author Marcos Alvarado
 */
public class Principal extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.init();
    }

    
    protected void init(){
        
        this.customTable1.getCustomModel().addData(new Object[] {new ButtonInfoPanel(ButtonInfoPanel.PROFIT, new Dimension(20, 20)), "textp", "text", "texto"});
        
        this.customRoundedInfoPanel1.setState(1);
        this.customRoundedInfoPanel2.setState(2);
        this.customRoundedInfoPanel3.setState(0);
    };
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customRoundedInfoPanel1 = new com.grupo06.View.customPanel.CustomRoundedInfoPanel();
        customRoundedInfoPanel2 = new com.grupo06.View.customPanel.CustomRoundedInfoPanel();
        customRoundedInfoPanel3 = new com.grupo06.View.customPanel.CustomRoundedInfoPanel();
        scrollPane1 = new com.grupo06.View.scroll.ScrollPane();
        customTable1 = new com.grupo06.View.CustomTable.CustomTable();

        setMaximumSize(new java.awt.Dimension(744, 640));
        setMinimumSize(new java.awt.Dimension(744, 640));

        scrollPane1.setOpaque(false);
        scrollPane1.setViewportView(customTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(customRoundedInfoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customRoundedInfoPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customRoundedInfoPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(customRoundedInfoPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(customRoundedInfoPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customRoundedInfoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.grupo06.View.customPanel.CustomRoundedInfoPanel customRoundedInfoPanel1;
    private com.grupo06.View.customPanel.CustomRoundedInfoPanel customRoundedInfoPanel2;
    private com.grupo06.View.customPanel.CustomRoundedInfoPanel customRoundedInfoPanel3;
    private com.grupo06.View.CustomTable.CustomTable customTable1;
    private com.grupo06.View.scroll.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
