/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.grupo06.View.customPanel;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import javax.swing.ImageIcon;

/**
 *
 * @author Marcos Alvarado
 */
public class ButtonInfoPanel extends javax.swing.JPanel {
    
    public static final int PROFIT = 0;
    public static final int MONEY = 1;
    public static final int DEBT = 2;
    
    private int state = 0;
    
    private Dimension iconSize = new Dimension(30, 30);
    
    private Color color1 = new Color(0, 202, 78);

    public ButtonInfoPanel() {
        setOpaque(false);
        initComponents();
    }
    
    public ButtonInfoPanel(int state, Dimension iconSize) {
        setOpaque(false);
        initComponents();
        this.iconSize = iconSize;        
        setState(state);
    }
    
    public int getState() {
        return state;
    }

    public void setState(int state) {
        this.state = state;
        switch (this.state) {
            case 0 -> {
                this.color1 = new Color(0, 202, 78);
                changeIcon("/com/grupo06/icon/arrowUp.png");
            }
            case 1 -> {
                this.color1 = new Color(255, 189, 68);
                changeIcon("/com/grupo06/icon/coin.png");
            }
            case 2 -> {
                this.color1 = new Color(255, 96, 92);
                changeIcon("/com/grupo06/icon/arrowDown.png");
            }
            default -> {
                this.color1 = new Color(0, 202, 78);
                changeIcon("/com/grupo06/icon/arrowUp.png");
            }
        }
        repaint();
    }
    
    public void changeIcon(String filePath) {
        
        int width = iconSize.width;
        int height = iconSize.height;
        
        ImageIcon originalIcon = new ImageIcon(getClass().getResource(filePath));
        Image img = originalIcon.getImage();
        Image scaledImage = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        ImageIcon newIcon = new ImageIcon(scaledImage);

        this.jLabel1.setIcon(newIcon);
    }
    
    @Override
    public void paintComponent(Graphics g) {
        
        super.paintComponent(g);
        // Set color to red
        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        g2d.setColor(this.color1);
        
        Dimension arcs = new Dimension(getWidth(), getHeight());
        int w = getWidth(), h = getHeight();
               
        // Draw a circle with center (200, 200) and radius 50
        
        
        g2d.fillRoundRect(0,0,
                w-1, h-1, arcs.width, arcs.height);
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
